language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: EnkT/YblNfgBgGXU3idtjF7NCBJN9CFygUgFEgXOverq47ubra1UcLQ5dAJSKl25rJZ/V1sExwBClpNv3jb12NhFE1mDlD30e9ffVpPuBIl4s0HJvpkTUn53ja5QTrXTgcAZVfbi/vtNY8CVUqfwBWVdEqJGydfJJXYQkjxBE3GxOg71T9i1gmT58g6VI7jNKOJv3PgPxmxW12woStxeNn8NQBSnE4T0SwS0PBMRYNAv1EfJS/LJTvX95fjrCWNjgzXadMttR08CHzpZrMX89y0qa8MTI3/sToa7XszLgrj2DX/tR/HhOQAquoF/RHYyja419fOGciads7CgN0zU38mBT//03ZajiJXz3+Tw7Lkza6NO5NoqIdQtWTxGkIBNsjpwBOmZDdHel27PNsQaRgs/j5X369GOGVlsMzAO0E/RcM6VQmRyn/YC1Gaa2Cod3zU5ic/unJ49gWuv/voHZ8v09fIwqCdQsFOO/8o9rF5NML8IDHn/xjPcdwKTuj80qaw73fVHJnFPRLoeiyxqrWh89kIh8OVdD47VSMelTPacmNsFuSWIWyFhqd6oD0xO1yfqB8OlXeBXnHiTzfv5+CbMbcFRRIFXv76HZs794RxRcyroQo6kJ/k6nxB6jtDE/Apg4N5tM2zPvWqXaIFXk7jPBuDa+zGeJVrGO/WKxUM=
  on:
    all_branches: true
