language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: VoPuDbz+qkSrXopUHnDXIh191MjtRIJoUoVczcXFIzH9dRKfZf3G3mpZ1YgYuEpFxm4yWsOL6elkYnx0aM6II8T3T8JoMm4jbMp8C+ZyAs1FjR41xCDCXrlUIKk8c73Di8EmkRsC8fcgXD6fMve81FL1R+lSPbfTqsy4CdkTraGI0ASIY1/gXJKQRKFQUsKe2J5D55KolnaWGrfqrWmMa7KNttvrAw2ZSIc6oBzMSkIX/hbfidPdDygXL+yMXu/ciJlyVrcVwVxFRDVT8LC07TovVjWqCEBT858GA5ZRXggRHQytMPtKLh+Zrs4dvwXQJP42o/tG4YGz8OaJGrcCnuD/aETywwsrC3HIcb+dTTH7M/6wLL7zM/05SpnvXjhRIrwaX54XWR7ZKdB/YXGB08WAmDYRJgDpjRaGrQ74NpsWdcuWfG5N4BqGUnHeJ2XBWphbc7Odi8SR4kUjXVNLSP5cxZ8CBGKF29RWjMueizZ/NGWEXk7hGLYXnZz7L3ciITY/s7As6lUtBwT5nqTFynk10SYXAOqZCszOeU4N8FSPyqgf7HmVlp3zZ5oIR3KsHFWlLP71qCm5C7WecvXMPeTv4+9XxLR92ERnc/F6LB3D9yYuay9Y8aEfRETsKnlBvzWcLfs/Sz+ZIiPmut1qODuBcPUnyybf8o6vzDzk7SY=
  on:
    all_branches: true
