language: java

jdk:
- oraclejdk8

deploy:
  provider: heroku
  api_key:
    secure: YjEHS9PTDxnUav2nl653ibXZetVK5/zVdw2h8ZeLKOuL2lJwAhIrg5Pv8KB4sege5ZXuQW9+cOzxNnDZEBQ7FaiBXelt9yyPN5BK0jH2MDck9a6i+xlBqcCbFT+h7H2IIj0GmVUYLeHifS3wiuCKlRDmygkyHRNRJrbn9Y0fc1jkkBaeuywvNibNtkpMMe76Up5irJpXN79cA2RtDuYgCxOjejXmhbT+YMUXtM1fz3W00OPdTJW6AFTwl7jZpdKDZPAgGvw8RC2fj9S76ooJOY3eph32ooJg/cfYYedr0/1OAUiOglMiTtGyVvEtkvfci8vInNghgXNUCFuQc2tJCTYwPBRcTZSnta6DX5rj62K2bjuqhTcYAsg39Ti/tdlERsxdQHjzwqs034CVzF2gVpYLLfhEy/Oq545WDQj6zA6Q58k0Ulhv6BLc0X2ppUdF4pu+vOWxKs1Q9Kb6593IB9rmm/CfMnsWpa0981Yb1a/fMl8Q5um/z/+qatwypNZeRKllW2nktjQ+FttyK82b6jC/wubRB7hi2os8FAKldWrC5shiSjaR8Gu/hoZrsEUOahu5ZWzEiGquz8a7V7rgWG6D7tPTKnHjDlfQLqy+Y/kiq/jLlF+mQLiq8TyjgeaGCy8i7cUQmnn6lHfJKIrNLmxtATYFPNr3d3mni7ctOlI=
