language: java

jdk:
  - oraclejdk8

deploy:
  provider: heroku
  api_key:
    secure: "SdD2CuRDMEwah6KRhs7Qroo4GT2+4jQomleyTNzDC3GF5iosNrKXnMEaqXkEwDxrT3cBkm3PdiLzdQAk5y5ZR/jNipvnmxw2HPcK8jW76xfv2lHGUUUNZfTnS2x/j7lAhlAmQjvFQHGxlPna/y56RjnJSIbLV4jVPsqMY+P38WbqW/7ebRDCEa7EBjmgHxKaOL24piNc5YaxJtI9KWdST1WlI3x+p9AVpddM3bE6OxkBzUlHdQqpgw44iUJ5iN78L9OgW11WeCY1QcBub61PSX7kAKct0GJ0rjAyo0/OZgo5ZQc2hq6TQ4SS9Te5BKBu1JuYKuUdFoLeQ6mOYBXErM6wvfMoFQ+PmwnUZvFrOheLdoSDJDNJVTF3uWRJ+bfPyIaqA9UC8By6jEGDCc31H/9b5KvFoZLcu0vc3JHdiHq7yyYb9QOHB78/JdwPDk6dXhIydjusDZojDUyXRKDnaGnoigBn/w/svw3ODo1T54dxVdI2c6OWWjPGLXxCALe8NqJQEJ5RmOmNOvc+cJ3WcSW3dL3WdUH4ZLYnTCuafw8wX0dAaci9r/X2UIVP25mwYS/jGZm0wVuVS/vaeuUmIuw6EuE4cn/fDj94VAsPUO9Fk/VocPlBIPgD03XQHbkXQYm3nwzZo7Z7CzoFFmFzmiOoo/ATxI1+LwHhPmQmYvw="
  on: heroku_deploy